### ISSUE TITLE
$.removeCookie didn't work for sub-path

### ISSUE THREAD

**Issue by scottstewartt** [carhartl/jquery-cookie#336]
Hi, I have a sub-path on my server that sets a cookie and haven't been able to get $.removeCookie to remove it. 
So, for example:
/subpath/subpage.html sets a cookie with $.cookie('testCookie', 'test', { path: '/subpath'});
then hitting /superpage.html executes $.removeCookie('testCookie', { path: '/subpath'});

However, executing $.cookie('testCookie', 'delete', { path: '/subpath', expires:0}); in /superpage.html did work. I would think that's basically what $.removeCookie is doing, but maybe not..

**Comment by mindware** [comment]
@scottstewartt can you confirm if you are still seeing this behaviour?

**Comment by carhartl** [comment]
Ah! I think the problem is that from the superpage, you don't have (read) access to the cookie that has been written with the sub path. The guard clause in the `$.removeCookie` function will return false:

```js
if $.cookie(key) === undefined) {
    return false;
}
```

@scottstewartt What is the return value of the (unsuccessful) call to `$.removeCookie`?

That's also why deleting the cookie manually by writing it with expires: 0 is successful (yes, removeCookie does the same behind the curtain). 

I've never taken this scenario into account. Said guard clause isn't by all means necessary I think.
