### ISSUE TITLE
Usage using npm

### ISSUE THREAD

**Issue by huglester** [carhartl/jquery-cookie#361]
Hello,

I do not quire understand, on how this should work using npm system?

// this works
var $ = require('jquery');

// 
var cookie = require('jquery.cookie');
but what now? how to work with this?
cookie('name', 'valuie'); does not work...

Thanks for any info! :)

**Comment by FagnerMartinsBrack** [comment]
Hi, currently it does not return the api when using `require("jquery.cookie")`. Since this is a jquery plugin it is bound to the jquery namespace, so if you do the following it is supposed to work (didn't tested though):

```javascript
var $ = require( "jquery" );
require( "jquery.cookie" );
!!$.cookie; // true
```

It was reported on https://github.com/carhartl/jquery-cookie/pull/330 and fixed in https://github.com/js-cookie/js-cookie/commit/3e816b8ab8a130ccc24e29966dbf98c04f66a6d3#diff-b686f7b30e7b0c4f5ed6cd2e87241704R136 (in the new repository), but it is not yet published on npm. If you want to use it you can download the code on https://github.com/js-cookie/js-cookie/blob/master/src/js.cookie.js (just the version is incorrect in the header, I will change that to `1.5.0-pre` in a few minutes).

With the code above you can do something like this:

```javascript
var cookie = require( "js.cookie" );
!!cookie.set; // true
!!cookie.get; // true
!!cookie.remove; // true
```

Please report on github.com/js-cookie/js-cookie if you have any issues.

**Comment by huglester** [comment]
Thank you, it works!

**Comment by FagnerMartinsBrack** [comment]
I'm glad it worked xD. Follow https://github.com/js-cookie/js-cookie/ repository, there will be a lot of interesting implementations in the next weeks :)

**Comment by FagnerMartinsBrack** [comment]
@huglester 

I'm glad it worked xD. Follow https://github.com/js-cookie/js-cookie/ repository, there will be a lot of interesting implementations in the next weeks :)

**Comment by huglester** [comment]
@FagnerMartinsBrack it is already new home for my jquery cookie thing:))) starting with npm packages and it's stuff!
