### ISSUE TITLE
plugins.jquery.com/cookie/ links to old page on github

### ISSUE THREAD

**Issue by sswam** [carhartl/jquery-cookie#371]
http://plugins.jquery.com/cookie/ links to the old page on github.

It should link to the new one https://github.com/js-cookie/js-cookie

**Comment by FagnerMartinsBrack** [comment]
The homepage of `plugins.jquery.com` says:

> The jQuery Plugin Registry is in read-only mode. New plugin releases will not be processed.

It is stuck on version 1.4.1 there.

Also, even if we could change it, the renamed project (`js-cookie`) does not have jQuery (`$`) as a dependency from the version 2.0 and onwards. It probably doesn't make sense to change the project URL in jquery plugins page, but if possible it would be worth mentioning the new project for future reference, because there's some traffic coming from http://plugins.jquery.com/cookie/ URL.

@carhartl thoughts?

**Comment by carhartl** [comment]
JS Cookie is not a jQuery plugin, we should leave the predecessor untouched. 

Of course it's worth mentioning there that we've moved forward.

**Comment by FagnerMartinsBrack** [comment]
> Of course it's worth mentioning there that we've moved forward.

Any idea on how to do it?
I wonder if `New plugin releases will not be processed` means that it won't accept new plugins or it won't accept new releases (even for plugins that are already there).

**Comment by carhartl** [comment]
@FagnerMartinsBrack Not sure if it's possible to still edit the plugin page. Last time I tried to sign in it didn't work but that may have been a temporary problem. I'm going to try again.

**Comment by carhartl** [comment]
It doesn't look like I can even sign in any longer. I don't think it's worth it to create a new release just to change the description to include a link (given that this new release would be processed). After all, it is mentioned in a prominent location in this repository's readme. And if one is really wondering about a new release or the latest code she might end up here anyway.

What do you think @FagnerMartinsBrack?

**Comment by FagnerMartinsBrack** [comment]
> It doesn't look like I can even sign in any longer.

Well, if you can't sign in, then there's nothing we can do xD. The only reason to mention the change in the plugins page is because that is one of the main sources of traffic for this repository, most ppl don't even care there is a documentation in the README and go straight to copy/paste the code from github UI =/.

**Comment by sswam** [comment]
When I raised this issue I wasn't aware that the new version of js-cookie is no longer a jquery plugin.  Now that I'm aware of that, I don't think it's necessary to link to it direct from the jquery plugins site.  The older jquery plugin already links to the new page, that's good enough.  Sorry for the trouble!
