### ISSUE TITLE
Line Break

### ISSUE THREAD

**Issue by mborah** [carhartl/jquery-cookie#379]
My code in HTML page

a href="abcd.html" class="link">My Link</a>

$(document).ready(function () {
  $(".link").on("click", function () {  
    $.cookie('myCookie', 'In this string I want to break the Line like \n second line starts', { expires: 2  , path: '/' });  
  });
});

**Comment by carhartl** [comment]
Yes, you'll have to add a `\n` in order to produce a line break in that string.

```
>> "foo\nbar"
"foo
bar"
```

Closing, as it's not really a problem with the plugin.

**Comment by mborah** [comment]
Sorry, but \n is not breaking my line in the output.

I tried with both:
In this string I want to break the Line like \n second line starts
In this string I want to break the Line like\nsecond line starts.

I don't know why it is not working for me.

**Comment by FagnerMartinsBrack** [comment]
@mborah The Line Feed (LF) is a control character (CTL) and therefore it is NOT allowed in the cookie value, as per [RFC 6265](https://tools.ietf.org/html/rfc6265#section-4.1.1)

**Comment by carhartl** [comment]
Ah, thanks @FagnerMartinsBrack :+1: 

So, a browser likely silently swallows that character.

**Comment by FagnerMartinsBrack** [comment]
I have no idea which browsers it breaks and how it breaks. When I was building the encoding tests, Safari and IE seemed to be the worst for invalid chars. Sometimes in Safari it ignored the value, and sometimes it ignored everything after the offending char or even prevented the whole cookie to be set.

Since the behavior is undefined, I like to assume that if you do something that goes against the RFC the browser will turn off your computer and it will never turn on again ;D

**Comment by mborah** [comment]
@FagnerMartinsBrack and @carhartl  ... Thanks for your reply.. 
Same here, even for me sometimes in Mozilla it ignored the value, and sometimes it ignored everything or sometime shows the whole character including "\n". God Knows uffff....

So, finally what shud I do? Should I set two different cookies for different lines? Any suggestion would be helpful.

**Comment by carhartl** [comment]
You could use say "__" to denote a line break, then, when reading a cookie, replace that again with a real line break using a converter function:

``` js
$.cookie("foo", "first__second");
$.cookie("foo", function (s) {
    return s.replace("__", "\n");
});
```

**Comment by mborah** [comment]
Thanks I will try with that.

**Comment by FagnerMartinsBrack** [comment]
Or you can post this issue in the new [JavaScript Cookie](https://github.com/js-cookie/js-cookie) project. I just ignored the control characters encode handling because I never thought someone would create a cookie with that. Supporting it costs unnecessary bytes to the codebase, but LF seems reasonable.
