### ISSUE TITLE
Cookies deleted when page open without query parameters

### ISSUE THREAD

**Issue by AviOmicron** [carhartl/jquery-cookie#385]
When I open my site with query parameters attached to the domain the plugin works perfectly.
www.mysite.com?utm_campaign=campaign1&utm_source=test
returns indeed: 

Campaign : campaign1
Source: test

However, as soon as I open the domain/page www.mysite.com without any added query parameters, the cookies are emptied. And return empty fields:

Campaign: 
Source: 

How can I prevent this?

**Comment by FagnerMartinsBrack** [comment]
Hi @AviOmicron, there is not enough information to provide a concrete response.

We recommend that you open support related issues on [Stackoverflow under the tag js-cookie](stackoverflow.com/questions/tagged/js-cookie) or the tag [jquery-cookie](http://stackoverflow.com/questions/tagged/jquery-cookie). It is much more likely that you will receive a fast satisfactory response there. Also, StackOverflow has better SEO and therefore the answers to your questions will be able to help future googlers better.

I would like to suggest that before asking the questions you look into the http://sscce.org, there you can see a way to reduce your code in order to track the root cause of the problem.

I hope it helps.

**Comment by FagnerMartinsBrack** [comment]
Closing due to the lack of feedback from the OP.
