### ISSUE TITLE
Disable issues?

### ISSUE THREAD

**Issue by carhartl** [carhartl/jquery-cookie#389]
We moved forward with the project, should we disable issues for this legacy repository? 

We're asking everyone to use the newer lib, and also to report bugs over there.

**Comment by FagnerMartinsBrack** [comment]
The amount of issues opened is not too big, it's not like we can't manage it. Sometimes there are issues like #380 that could help us to determine if the way we are reporting the new repository is efficient or not. Other issues can just be closed, such as #387.

Also, there are cross-links between both repositories. So closing the issues page might break the links?

I still think the issues page is relevant because this repository still receives a considerable amount of Traffic and feedback is always welcome.

**Comment by FagnerMartinsBrack** [comment]
@carhartl I have created #392, so that anyone coming to the issues page without reading the README will see that before opening a new issue.

It doesn't happen often, we had just one issue created here this month 1 hour ago: #391. With this last strategy I guess there will be fewer, or hopefully none.

Can I close this?
